name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build
        env:
          DENO_DIR: .deno
        run: deno task build

      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: "pretxel-potato-daily"
          root: dist
          entrypoint: https://deno.land/std@0.224.0/http/file_server.ts
